name: Bug Report
description: Create a bug report to help developers reproduce and fix an issue.
body:
  - type: markdown
    attributes:
      value: |
        # **Please read the following guidelines. Follow all instructions or else your issue is subject to closure.**
        
        Read all sections within this template carefully and follow the instructions given within each step. Include as many details as possible.
        If you are reporting an issue found in another branch or codebase, your issue will be closed.
  - type: checkboxes
    id: reporting-requirements
    attributes:
      label: "YOU MUST CONFIRM THE FOLLOWING STATEMENTS TO POST A BUG REPORT HERE"
      description: |
        Before posting a bug report to this repo, please confirm all three of the following statements or your issue **WILL** be closed.
        We are **NOT** NovaSector's developers, and will **NOT** fix issues that are solely related to unmodified NovaSector.
        We also do **NOT** have infinite time in our day, so all bugs reported must be consistently reproduceable in one or more different ways.
      options:
      - label: I have reproduced this bug on **only** ExobytechNova, and not the vanilla (unmodified) version of NovaSector. This means the bug doesn't happen on NovaSector's main branch, but does happen on this fork.
        required: false
      - label: I have reproduced this bug consistently, such that the developers of ExobytechNova will have no issue tracking and fixing the bug.
        required: false
      - label: I solemnly swear that if I am lying, I am a big idiot and may be blocked from contributing to ExobytechNova by its developers as a direct consequence of my misdeeds.
        required: false
  - type: input
    id: reporting-version
    attributes:
      label: "Client Version:"
      description: |
        The BYOND version you are using to report this issue. You can find this information in the bottom left corner of the "About BYOND" window in the BYOND client.
        It is strongly recommended that you include this, especially for concerns on the visual aspects of the game.
      placeholder: "xxx.xxxx"
    validations:
      required: false
  - type: textarea
    id: issue-summary
    attributes:
      label: "Issue Summary:"
      description: |
        Briefly explain your issue in a few plain sentences. You may copy and paste the issue title here if it is suitable.
      placeholder: |
        "When I do X, Y happens instead of Z."
        "X on Y map has Z issue."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior:"
      description: |
        Provide here a clear and concise description of what you expected to happen.
      placeholder: |
        "When I do X, Y should occur instead of Z."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Reproduction Steps:"
      description: |
        Describe the steps to reproduce the issue in detail. Include any relevant information, such as the map, round type, and any other factors that may be relevant.
        If it is a runtime-related error, please include the runtime here as that is pertient information.
        
        Issues are not for oddities introduced by admin varedits. Ensure the bug you are reporting can occur and be reproduced within in normal circumstances.
      placeholder: |
        1. Go to the X location
        2. Do Y action
        3. Observe Z result
    validations:
      required: true
